import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Banner from "../components/Banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-full min-h-screen w-full flex-col bg-gradient-to-b from-yellow-50/20 via-amber-100/60 to-yellow-50/40">
        <Header />
        <main className="flex  flex-1 ">
          <Banner />
        </main>
      </div>
    </>
  );
}
